#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libXinerama
Version  : 1.1.3
Release  : 7
URL      : http://xorg.freedesktop.org/releases/individual/lib/libXinerama-1.1.3.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/lib/libXinerama-1.1.3.tar.gz
Summary  : The Xinerama Library
Group    : Development/Tools
License  : MIT
Requires: libXinerama-lib
Requires: libXinerama-doc
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xextproto)
BuildRequires : pkgconfig(xineramaproto)
BuildRequires : pkgconfig(xorg-macros)

%description
libXinerama - API for Xinerama extension to X11 Protocol
All questions regarding this software should be directed at the
Xorg mailing list:

%package dev
Summary: dev components for the libXinerama package.
Group: Development
Requires: libXinerama-lib
Provides: libXinerama-devel

%description dev
dev components for the libXinerama package.


%package doc
Summary: doc components for the libXinerama package.
Group: Documentation

%description doc
doc components for the libXinerama package.


%package lib
Summary: lib components for the libXinerama package.
Group: Libraries

%description lib
lib components for the libXinerama package.


%prep
%setup -q -n libXinerama-1.1.3

%build
export LANG=C
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/extensions/Xinerama.h
/usr/include/X11/extensions/panoramiXext.h
/usr/lib64/libXinerama.so
/usr/lib64/pkgconfig/xinerama.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libXinerama.so.1
/usr/lib64/libXinerama.so.1.0.0
