#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libXinerama
Version  : 1.1.4
Release  : 13
URL      : http://xorg.freedesktop.org/releases/individual/lib/libXinerama-1.1.4.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/lib/libXinerama-1.1.4.tar.gz
Summary  : The Xinerama Library
Group    : Development/Tools
License  : MIT
Requires: libXinerama-lib
Requires: libXinerama-license
Requires: libXinerama-man
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : pkg-config
BuildRequires : pkgconfig(32x11)
BuildRequires : pkgconfig(32xext)
BuildRequires : pkgconfig(32xextproto)
BuildRequires : pkgconfig(32xineramaproto)
BuildRequires : pkgconfig(32xorg-macros)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xextproto)
BuildRequires : pkgconfig(xineramaproto)
BuildRequires : pkgconfig(xorg-macros)

%description
libXinerama - API for Xinerama extension to X11 Protocol
All questions regarding this software should be directed at the
Xorg mailing list:

%package dev
Summary: dev components for the libXinerama package.
Group: Development
Requires: libXinerama-lib
Provides: libXinerama-devel

%description dev
dev components for the libXinerama package.


%package dev32
Summary: dev32 components for the libXinerama package.
Group: Default
Requires: libXinerama-lib32
Requires: libXinerama-dev

%description dev32
dev32 components for the libXinerama package.


%package lib
Summary: lib components for the libXinerama package.
Group: Libraries
Requires: libXinerama-license

%description lib
lib components for the libXinerama package.


%package lib32
Summary: lib32 components for the libXinerama package.
Group: Default
Requires: libXinerama-license

%description lib32
lib32 components for the libXinerama package.


%package license
Summary: license components for the libXinerama package.
Group: Default

%description license
license components for the libXinerama package.


%package man
Summary: man components for the libXinerama package.
Group: Default

%description man
man components for the libXinerama package.


%prep
%setup -q -n libXinerama-1.1.4
pushd ..
cp -a libXinerama-1.1.4 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1530842697
export CFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export FFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
%configure --disable-static
make  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export CFLAGS="$CFLAGS -m32"
export CXXFLAGS="$CXXFLAGS -m32"
export LDFLAGS="$LDFLAGS -m32"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1530842697
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/libXinerama
cp COPYING %{buildroot}/usr/share/doc/libXinerama/COPYING
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/extensions/Xinerama.h
/usr/include/X11/extensions/panoramiXext.h
/usr/lib64/libXinerama.so
/usr/lib64/pkgconfig/xinerama.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libXinerama.so
/usr/lib32/pkgconfig/32xinerama.pc
/usr/lib32/pkgconfig/xinerama.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libXinerama.so.1
/usr/lib64/libXinerama.so.1.0.0

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libXinerama.so.1
/usr/lib32/libXinerama.so.1.0.0

%files license
%defattr(-,root,root,-)
/usr/share/doc/libXinerama/COPYING

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Xinerama.3
/usr/share/man/man3/XineramaIsActive.3
/usr/share/man/man3/XineramaQueryExtension.3
/usr/share/man/man3/XineramaQueryScreens.3
/usr/share/man/man3/XineramaQueryVersion.3
